---
development:
  cloud_name: dm2frsbrc
  api_key: '599567465899867'
  api_secret: 0hJYTuPfITxu1W7q-lEISLMEIs0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dm2frsbrc
  api_key: '599567465899867'
  api_secret: 0hJYTuPfITxu1W7q-lEISLMEIs0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dm2frsbrc
  api_key: '599567465899867'
  api_secret: 0hJYTuPfITxu1W7q-lEISLMEIs0
  enhance_image_tag: true
  static_image_support: false
